// Lang worker — the Web Worker shell around lang-service.ts. The whole TS
// compiler lives in this bundle, off the main thread; startup fetches
// lang-env.json (generated by scripts/gen-lang-env.js) and stands the
// service up.

import { createLangService, type LangService, type LangCompletions, type LangSymbolInfo, type LangSignatureHelp, type LangEnv, type EditorLang } from './lang-service.js'

// `lang` picks the surface the query runs against (default 'dsl'). One service
// per language, created lazily: most sessions never open a hydra cell.
export type LangRequest = { lang?: EditorLang } & (
  | { id: number; kind: 'completions'; text: string; pos: number }
  | { id: number; kind: 'details'; text: string; pos: number; name: string }
  | { id: number; kind: 'quickinfo'; text: string; pos: number }
  | { id: number; kind: 'signature'; text: string; pos: number; triggerChar?: string }
)

export type LangResult = LangCompletions | LangSymbolInfo | LangSignatureHelp | null

export type LangResponse =
  | { id: number; ok: true; result: LangResult }
  | { id: number; ok: false; error: string }

// Sent once at startup, before any responses.
export type LangReady = { kind: 'ready' } | { kind: 'init-failed'; error: string }

function handle(service: LangService, req: LangRequest): LangResult {
  switch (req.kind) {
    case 'completions': return service.completionsAt(req.text, req.pos)
    case 'details': return service.detailsAt(req.text, req.pos, req.name)
    case 'quickinfo': return service.quickInfoAt(req.text, req.pos)
    case 'signature': return service.signatureHelpAt(req.text, req.pos, req.triggerChar)
  }
}

const post = self.postMessage.bind(self) as (msg: unknown) => void

const ready: Promise<((lang: EditorLang) => LangService) | null> = (async () => {
  const res = await fetch(new URL('lang-env.json', self.location.href))
  if (!res.ok) throw new Error(`lang-env.json: HTTP ${res.status}`)
  const env = (await res.json()) as LangEnv
  const services = new Map<EditorLang, LangService>()
  const serviceFor = (lang: EditorLang): LangService => {
    let s = services.get(lang)
    if (!s) { s = createLangService(env, lang); services.set(lang, s) }
    return s
  }
  serviceFor('dsl').completionsAt('table("x").', 11) // warmup so the first keystroke doesn't pay lazy binding
  return serviceFor
})().then(
  (serviceFor) => { post({ kind: 'ready' } satisfies LangReady); return serviceFor },
  (err: unknown) => {
    console.error('lang worker: init failed:', err)
    post({ kind: 'init-failed', error: err instanceof Error ? err.message : String(err) } satisfies LangReady)
    return null
  },
)

self.addEventListener('message', (e) => {
  const req = (e as MessageEvent).data as LangRequest
  void ready.then((serviceFor) => {
    if (!serviceFor) { post({ id: req.id, ok: false, error: 'not initialized' } satisfies LangResponse); return }
    try {
      post({ id: req.id, ok: true, result: handle(serviceFor(req.lang ?? 'dsl'), req) } satisfies LangResponse)
    } catch (err) {
      post({ id: req.id, ok: false, error: err instanceof Error ? err.message : String(err) } satisfies LangResponse)
    }
  })
})
