// Lang worker — the humble Web Worker shell around lang-service.ts.
// ----------------------------------------------------------------------------
// TypeScript (the whole compiler) lives in this bundle, off the main thread.
// On startup it fetches the language environment (lang-env.json, generated by
// scripts/gen-lang-env.js and served alongside this bundle), stands the
// service up, and answers editor queries. A warmup query runs at init so the
// first real keystroke doesn't pay the checker's lazy-binding cost.

import { createLangService, type LangService, type LangCompletions, type LangSymbolInfo, type LangSignatureHelp, type LangEnv } from './lang-service.js'

export type LangRequest =
  | { id: number; kind: 'completions'; text: string; pos: number }
  | { id: number; kind: 'details'; text: string; pos: number; name: string }
  | { id: number; kind: 'quickinfo'; text: string; pos: number }
  | { id: number; kind: 'signature'; text: string; pos: number; triggerChar?: string }

export type LangResult = LangCompletions | LangSymbolInfo | LangSignatureHelp | null

export type LangResponse =
  | { id: number; ok: true; result: LangResult }
  | { id: number; ok: false; error: string }

// Sent once at startup, before any responses.
export type LangReady = { kind: 'ready' } | { kind: 'init-failed'; error: string }

function handle(service: LangService, req: LangRequest): LangResult {
  switch (req.kind) {
    case 'completions': return service.completionsAt(req.text, req.pos)
    case 'details': return service.detailsAt(req.text, req.pos, req.name)
    case 'quickinfo': return service.quickInfoAt(req.text, req.pos)
    case 'signature': return service.signatureHelpAt(req.text, req.pos, req.triggerChar)
  }
}

const post = self.postMessage.bind(self) as (msg: unknown) => void

const ready: Promise<LangService | null> = (async () => {
  const res = await fetch(new URL('lang-env.json', self.location.href))
  if (!res.ok) throw new Error(`lang-env.json: HTTP ${res.status}`)
  const env = (await res.json()) as LangEnv
  const service = createLangService(env)
  service.completionsAt('table("x").', 11) // warmup: bind libs + DSL types now
  return service
})().then(
  (service) => { post({ kind: 'ready' } satisfies LangReady); return service },
  (err: unknown) => {
    console.error('lang worker: init failed:', err)
    post({ kind: 'init-failed', error: err instanceof Error ? err.message : String(err) } satisfies LangReady)
    return null
  },
)

self.addEventListener('message', (e) => {
  const req = (e as MessageEvent).data as LangRequest
  void ready.then((service) => {
    if (!service) { post({ id: req.id, ok: false, error: 'not initialized' } satisfies LangResponse); return }
    try {
      post({ id: req.id, ok: true, result: handle(service, req) } satisfies LangResponse)
    } catch (err) {
      post({ id: req.id, ok: false, error: err instanceof Error ? err.message : String(err) } satisfies LangResponse)
    }
  })
})
